name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # berjalan setiap hari
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: wahidhendrawan
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/github-contribution-grid-snake.svg"
          message: "Generate Contribution Snake"
